create table abastecimento (id  bigserial not null, estado_pagamento varchar(255) not null, km_veiculo float8, litros float8, local varchar(255), preco float8, tipo_abastecimento varchar(255) not null, viagem_id int8, primary key (id));
create table cidade (id  bigserial not null, nome varchar(255), estado_id int8, primary key (id));
create table caixa_veiculo (id  bigserial not null, saldo float8, veiculo int8, primary key (id));
create table despesas (id  bigserial not null, data timestamp, descricao varchar(255), estado_pagamento varchar(255) not null, local varchar(255), preco float8, tipo_despesa varchar(255) not null, viagem_id int8, primary key (id));
create table endereco (id  bigserial not null, bairro varchar(255), cep varchar(255), complemento varchar(255), logradouro varchar(255), numero varchar(255), cidade_id int8, pessoa_id int8, transportadora_id int8, primary key (id));
create table estado (id  bigserial not null, nome varchar(255), primary key (id));
create table motorista (id  bigserial not null, categoria varchar(2), cnh_espelho int4, cnh_registro int4, num_seguranca int4, renach varchar(255), taxa_comissao float8, validade timestamp, cidade_emissao int8, pessoa_id int8, transportadora_id int8, primary key (id));
create table pedagio (id  bigserial not null, data_hora timestamp, descricao varchar(255), num_eixos int4, valor float8, viagem_id int8, primary key (id));
create table permission (id  bigserial not null, description varchar(255), primary key (id));
create table pessoa (id  bigserial not null, cpf varchar(14) not null, dt_nascimento timestamp, email varchar(255), mae varchar(255), nome varchar(255) not null, orgao_expedidor varchar(255), pai varchar(255), rg varchar(255), naturalidade int8, transportadora_id int8, uf int8, primary key (id));
create table telefone (pessoa_id int8 not null, telefones varchar(255), transportadora_id int8 not null);
create table tipo_veiculo (id  bigserial not null, descricao varchar(255) not null, primary key (id));
create table transportadora (id  bigserial not null, rntrc varchar(255), cpf_cnpj varchar(19) not null, email varchar(255), nome varchar(255) not null, tipo varchar(255) not null, vencimento_rntrc timestamp, primary key (id));
create table user_permission (id_user int8 not null, id_permission int8 not null);
create table users (id  bigserial not null, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, password varchar(255), user_name varchar(255), pessoa_id int8, transportadora_id int8, primary key (id));
create table veiculos (id  bigserial not null, ano_fabricaco int4, ano_modelo int4, chassi varchar(255), cor varchar(255), exercicio_doc int4, kilometragem float4, marca varchar(255), modelo varchar(255), placa varchar(255), renavam int4, cidade_emplacado int8, motorista int8, tipo int8, transportadora_id int8, primary key (id));
create table veiculos_conjuntos (veiculo_id int8 not null, conjunto_id int8 not null);
create table viagens (id  bigserial not null, data_final timestamp, data_inicial timestamp, estado_viagem varchar(255) not null, km_final float8, km_inicial float8, peso_tonelada float8, saldo_final float8, saldo_inicial float8, valor_frete float8, destino int8, motorista_id int8, origem int8, transportadora_id int8, veiculo_id int8, primary key (id));
alter table if exists pessoa add constraint UK_mc87q8fpvldpdyfo9o5633o5l unique (email);
alter table if exists transportadora add constraint UK_2jgf6hqbueowvvgdkpfjgtc5d unique (rntrc);
alter table if exists transportadora add constraint UK_jdetrbn93bypt69v543yp0tlc unique (email);
alter table if exists users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table if exists abastecimento add constraint FKchifm3fyycnq8h7um1hy5yek0 foreign key (viagem_id) references viagens;
alter table if exists caixa_veiculo add constraint FKl9cb0ksboe02oy6nbjoqse16w foreign key (veiculo) references veiculos;
alter table if exists cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado;
alter table if exists despesas add constraint FKj06ie0tmjo4smr3pxx5rt16g6 foreign key (viagem_id) references viagens;
alter table if exists endereco add constraint FK8b1kcb3wucapb8dejshyn5fsx foreign key (cidade_id) references cidade;
alter table if exists endereco add constraint FKn1l2g0b74rqd9ywu29sva9sy9 foreign key (pessoa_id) references pessoa;
alter table if exists endereco add constraint FKowhbc4f55j3t3c0q1pmprhewe foreign key (transportadora_id) references transportadora;
alter table if exists motorista add constraint FK4r2o3keaex4e47ihb4xc4evlq foreign key (cidade_emissao) references cidade;
alter table if exists motorista add constraint FKa62akdheeydyxtubrqhxfb4t5 foreign key (pessoa_id) references pessoa;
alter table if exists motorista add constraint FKpiy23tnih81d8mp25kml3247h foreign key (transportadora_id) references transportadora;
alter table if exists pedagio add constraint FKopp9nytgqkxpqmb1alm7ql9y3 foreign key (viagem_id) references viagens;
alter table if exists pessoa add constraint FKk9bb1oaiiyw4haxa5xkcmvwbv foreign key (naturalidade) references cidade;
alter table if exists pessoa add constraint FKsbeoghpckrs4iekgtcsh6ub4y foreign key (transportadora_id) references transportadora;
alter table if exists pessoa add constraint FKkwnui25v8ansen0wqbefxi81a foreign key (uf) references estado;
alter table if exists telefone add constraint FKdfopyen4k14hhqgi17u5ct0h3 foreign key (pessoa_id) references pessoa;
alter table if exists telefone add constraint FKh3m2bmihf1fym9ihggwp1j4gn foreign key (transportadora_id) references transportadora;
alter table if exists user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table if exists user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;
alter table if exists users add constraint FKk0gedw1ip5lqsps2av7jknbex foreign key (pessoa_id) references pessoa;
alter table if exists users add constraint FKlr4ba5fqtha1q53noxdhvdh7b foreign key (transportadora_id) references transportadora;
alter table if exists veiculos add constraint FK8wdqow5drstlqw4gvsx53rgu foreign key (cidade_emplacado) references cidade;
alter table if exists veiculos add constraint FKt4mnq57ym14kkg4guhc68o1m6 foreign key (motorista) references motorista;
alter table if exists veiculos add constraint FK862x3gfqgn2eixcak2668b57x foreign key (tipo) references tipo_veiculo;
alter table if exists veiculos add constraint FK40oxt0cfulb9kp66f8jaceom6 foreign key (transportadora_id) references transportadora;
alter table if exists veiculos_conjuntos add constraint FKkbnvc1amkkid19tqxnybb1u3j foreign key (conjunto_id) references veiculos;
alter table if exists veiculos_conjuntos add constraint FKiy3g2eekdsg4gbbh43hts2ae5 foreign key (veiculo_id) references veiculos;
alter table if exists viagens add constraint FKj5c4lha9ijes6qquwqm2cd10s foreign key (destino) references cidade;
alter table if exists viagens add constraint FKbqk5fb5et4pj0dnj4krm0ed9w foreign key (motorista_id) references motorista;
alter table if exists viagens add constraint FKr53sjcop7c7yuv5b18gfvhgfb foreign key (origem) references cidade;
alter table if exists viagens add constraint FKdq6y89gi3njlc46h06y6kd4eo foreign key (transportadora_id) references transportadora;
alter table if exists viagens add constraint FK6yogg4wku31cttsf4ei0dteif foreign key (veiculo_id) references veiculos;